import { useState } from 'react'
import { AlertTriangle, CheckCircle, Copy, ExternalLink, Check, ChevronDown, ChevronUp, Image as ImageIcon } from 'lucide-react'

function toMarkdown(report) {
  if (!report) return ''
  const steps = (report.steps || []).map(s => `- Step ${s.step}: ${s.thought} → \`${s.action} ${s.target_id} ${s.value || ''}\``).join('\n')
  return `# Bug Report — Omni-QA Agent
**URL:** ${report.url || ''}
**Verdict:** ${report.verdict || ''}
**Summary:** ${report.summary || ''}
**Screenshot:** ${report.screenshot_url || 'none'}

## Steps
${steps || '- none'}

## Console
\`\`\`
${(report.console_errors || 'no errors').slice(0, 2000)}
\`\`\`
---
*Generated by Omni-QA Agent — ${new Date().toISOString()}*
`
}

function Card({ report }) {
  const [open, setOpen] = useState(false)
  const [toast, setToast] = useState(false)
  if (!report) return null
  const v = report.verdict
  const isBug = v === 'BUG_FOUND'
  const isFailed = v === 'FAILED'
  const isClean = v === 'CLEAN'
  const steps = report.steps || []
  const imgSrc = report.screenshot_b64 || report.screenshot_url
  async function handleExport() {
    const md = toMarkdown(report)
    await navigator.clipboard.writeText(md)
    setToast(true); setTimeout(()=>setToast(false), 2200)
  }
  const badgeCls = isBug ? 'bg-red-500/15 text-red-300 border-red-500/30' : isFailed ? 'bg-amber-500/15 text-amber-300 border-amber-500/30' : 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30'
  const BadgeIcon = isBug ? AlertTriangle : isFailed ? AlertTriangle : CheckCircle
  return (
    <div className="bg-[#14141c] border border-white/5 rounded-2xl p-5 space-y-3 hover:border-violet-500/40 transition-all hover:shadow-lg hover:shadow-violet-500/10 flex flex-col">
      <div className="flex items-center justify-between gap-2">
        <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold tracking-wide border ${badgeCls}`}>
          <BadgeIcon size={12}/> {v}
        </span>
        <span className={`text-[10px] px-2 py-0.5 rounded-full border font-medium ${isBug ? 'bg-red-500/10 text-red-300 border-red-500/20' : isFailed ? 'bg-amber-500/10 text-amber-300 border-amber-500/20' : 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20'}`}>{isBug ? 'HIGH' : isFailed ? 'MED' : 'LOW'} severity</span>
      </div>
      <div className="text-xs text-slate-400 truncate">{report.url}</div>
      <h3 className="font-semibold text-sm leading-snug line-clamp-2">{report.summary || 'Report ready'}</h3>

      {imgSrc && (
        <a href={imgSrc} target="_blank" rel="noreferrer" className="block rounded-xl overflow-hidden border border-white/10 bg-black group">
          <img src={imgSrc} alt="evidence" className="w-full h-36 object-cover group-hover:opacity-90 transition" />
          <div className="text-[10px] text-slate-400 px-2 py-1 flex items-center gap-1"><ImageIcon size={10}/> screenshot — click to open</div>
        </a>
      )}

      <button onClick={()=>setOpen(!open)} className="flex items-center gap-1 text-xs text-violet-300 hover:text-violet-200">
        {open ? <ChevronUp size={12}/> : <ChevronDown size={12}/>} Steps ({steps.length})
      </button>
      {open && (
        <div className="space-y-1 max-h-28 overflow-auto pr-1 text-xs">
          {steps.slice(0,8).map(s=>(
            <div key={s.step} className="flex gap-2 text-slate-400"><span className="text-violet-400 font-mono">{s.step}.</span><span className="flex-1 truncate">{s.thought?.slice(0,80)}</span><span className="text-cyan-400 font-mono">{s.action}</span></div>
          ))}
        </div>
      )}

      {report.console_errors && <pre className="bg-slate-950 rounded-xl p-2.5 text-[11px] overflow-auto max-h-20 text-slate-400 border border-white/5 whitespace-pre-wrap break-words">{report.console_errors.slice(0,700)}</pre>}

      <div className="flex gap-2 pt-2 mt-auto">
        <button onClick={handleExport} className="flex-1 flex items-center justify-center gap-2 bg-violet-600 hover:bg-violet-500 text-white rounded-xl py-2 text-xs font-semibold transition"> <Copy size={14}/> Export</button>
        <a href={report.url} target="_blank" rel="noreferrer" className="px-3 py-2 border border-white/10 rounded-xl text-xs flex items-center gap-1 hover:bg-white/5 transition"><ExternalLink size={14}/></a>
      </div>
      {toast && <div className="fixed bottom-4 right-4 bg-emerald-600 text-white px-4 py-2.5 rounded-xl shadow-xl flex items-center gap-2 text-xs font-semibold z-50 animate-in"><Check size={14}/> Copied — paste into GitHub!</div>}
    </div>
  )
}

export default function IssueCards({ report, reports }) {
  const list = reports && reports.length ? reports : (report ? [report] : [])
  if (list.length===0) return <div className="text-slate-400 text-sm border border-dashed border-white/10 rounded-2xl p-8 text-center bg-[#14141c]/50">No issues yet — start a mission to see evidence cards</div>
  return (
    <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">
      {list.map((r,i)=><Card key={r.session_id||r.id||i} report={r}/>)}
    </div>
  )
}
